// <auto-generated />
using System;
using BusTicketReservation.Data.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusTicketReservation.Data.Migrations
{
    [DbContext(typeof(BusContext))]
    [Migration("20221125110031_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("BusTicketReservation.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = 1,
                            SeatCapacity = 40
                        },
                        new
                        {
                            BusId = 2,
                            SeatCapacity = 40
                        },
                        new
                        {
                            BusId = 3,
                            SeatCapacity = 40
                        },
                        new
                        {
                            BusId = 4,
                            SeatCapacity = 40
                        },
                        new
                        {
                            BusId = 5,
                            SeatCapacity = 40
                        },
                        new
                        {
                            BusId = 6,
                            SeatCapacity = 40
                        });
                });

            modelBuilder.Entity("BusTicketReservation.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "İstanbul"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Kocaeli"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Düzce"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Samsun"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Ordu"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Antalya"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Afyon"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Kütahya"
                        });
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = 1,
                            Email = "iremgunal@gmail.com",
                            FirstName = "İrem",
                            LastName = "Günal",
                            PhoneNumber = "01234567891"
                        },
                        new
                        {
                            PassengerId = 2,
                            Email = "enverkorkmaz17@gmail.com",
                            FirstName = "Enver",
                            LastName = "Korkmaz",
                            PhoneNumber = "01234567892"
                        });
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("BusId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            BusId = 1,
                            PassengerId = 1,
                            SeatNo = 1,
                            TripId = 1
                        });
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromWhereId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToWhereId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TripTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TripId");

                    b.HasIndex("BusId");

                    b.HasIndex("FromWhereId");

                    b.HasIndex("ToWhereId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 429m,
                            ToWhereId = 5,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 2,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 129m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 3,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 189m,
                            ToWhereId = 3,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 4,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 399m,
                            ToWhereId = 4,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 5,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 149m,
                            ToWhereId = 3,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 6,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 429m,
                            ToWhereId = 4,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 7,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 469m,
                            ToWhereId = 5,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 8,
                            BusId = 1,
                            FromWhereId = 3,
                            Price = 419m,
                            ToWhereId = 4,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 9,
                            BusId = 1,
                            FromWhereId = 3,
                            Price = 449m,
                            ToWhereId = 5,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 10,
                            BusId = 1,
                            FromWhereId = 4,
                            Price = 119m,
                            ToWhereId = 5,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 11,
                            BusId = 1,
                            FromWhereId = 6,
                            Price = 469m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 12,
                            BusId = 1,
                            FromWhereId = 6,
                            Price = 169m,
                            ToWhereId = 7,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 13,
                            BusId = 1,
                            FromWhereId = 6,
                            Price = 229m,
                            ToWhereId = 8,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 14,
                            BusId = 1,
                            FromWhereId = 6,
                            Price = 399m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 15,
                            BusId = 1,
                            FromWhereId = 7,
                            Price = 449m,
                            ToWhereId = 8,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 16,
                            BusId = 1,
                            FromWhereId = 7,
                            Price = 149m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 17,
                            BusId = 1,
                            FromWhereId = 7,
                            Price = 129m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 18,
                            BusId = 1,
                            FromWhereId = 8,
                            Price = 449m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 19,
                            BusId = 1,
                            FromWhereId = 8,
                            Price = 449m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 20,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 149m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 21,
                            BusId = 1,
                            FromWhereId = 5,
                            Price = 399m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 22,
                            BusId = 1,
                            FromWhereId = 5,
                            Price = 129m,
                            ToWhereId = 4,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 23,
                            BusId = 1,
                            FromWhereId = 5,
                            Price = 229m,
                            ToWhereId = 3,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 24,
                            BusId = 1,
                            FromWhereId = 5,
                            Price = 229m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 25,
                            BusId = 1,
                            FromWhereId = 4,
                            Price = 229m,
                            ToWhereId = 3,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 26,
                            BusId = 1,
                            FromWhereId = 4,
                            Price = 399m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 27,
                            BusId = 1,
                            FromWhereId = 4,
                            Price = 449m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 28,
                            BusId = 1,
                            FromWhereId = 3,
                            Price = 449m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 29,
                            BusId = 1,
                            FromWhereId = 3,
                            Price = 229m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 30,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 129m,
                            ToWhereId = 1,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 31,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 449m,
                            ToWhereId = 6,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 32,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 419m,
                            ToWhereId = 2,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 33,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 229m,
                            ToWhereId = 8,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 34,
                            BusId = 1,
                            FromWhereId = 1,
                            Price = 419m,
                            ToWhereId = 7,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 35,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 419m,
                            ToWhereId = 8,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 36,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 149m,
                            ToWhereId = 7,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 37,
                            BusId = 1,
                            FromWhereId = 2,
                            Price = 419m,
                            ToWhereId = 6,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 38,
                            BusId = 1,
                            FromWhereId = 8,
                            Price = 229m,
                            ToWhereId = 7,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 39,
                            BusId = 1,
                            FromWhereId = 8,
                            Price = 449m,
                            ToWhereId = 6,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TripId = 40,
                            BusId = 1,
                            FromWhereId = 7,
                            Price = 399m,
                            ToWhereId = 6,
                            TripDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TripTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Ticket", b =>
                {
                    b.HasOne("BusTicketReservation.Entity.Bus", "Bus")
                        .WithMany("Tickets")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketReservation.Entity.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketReservation.Entity.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Trip", b =>
                {
                    b.HasOne("BusTicketReservation.Entity.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketReservation.Entity.City", "FromWhere")
                        .WithMany()
                        .HasForeignKey("FromWhereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketReservation.Entity.City", "ToWhere")
                        .WithMany()
                        .HasForeignKey("ToWhereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("FromWhere");

                    b.Navigation("ToWhere");
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Bus", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("BusTicketReservation.Entity.Trip", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
